import { defineArrayMember, defineField, defineType } from 'sanity'
import { HomeIcon } from '@sanity/icons'

const linkCardFields = [
	defineField({ name: 'title', type: 'string', validation: (Rule) => Rule.required() }),
	defineField({ name: 'description', type: 'text', rows: 3 }),
	defineField({ name: 'href', title: 'Link URL', type: 'string', validation: (Rule) => Rule.required() }),
	defineField({ name: 'linkLabel', title: 'Link label', type: 'string' }),
]

const sectionHeaderFields = [
	defineField({ name: 'eyebrow', type: 'string' }),
	defineField({ name: 'heading', type: 'string', validation: (Rule) => Rule.required() }),
	defineField({ name: 'body', type: 'text', rows: 4 }),
]

const defaultHomepage = {
	title: 'Comparison One Homepage',
	heroEyebrow: 'Australian SME funding readiness',
	heroHeadline: 'Avoid applying blind for business funding',
	heroSubtitle: 'Comparison One helps Australian SME owners check the funding path before the lender. See what lenders may ask for, what documents to prepare, and which product type may fit the cash-flow problem before you send an application.',
	heroImage: '/finview/hero_img.png',
	heroImageAlt: 'Australian business owner reviewing funding readiness before applying',
	primaryCtaLabel: 'Check funding readiness',
	secondaryCtaLabel: 'See document checklist',
	secondaryCtaHref: '/blog/business-loan-requirements-australia',
	trustStrip: 'Documents first • Product fit before lender fit • Bank, non-bank and specialist pathways',
	whyEyebrow: 'Why Comparison One',
	whyHeading: 'Compare the funding path before you compare the lender',
	whyBody: 'Most comparison sites begin with the product name. Comparison One starts with the reason cash is needed, the timing pressure, the documents available and the repayment source.',
	whyCards: [
		{ title: 'Know what lenders will check', description: 'Revenue, trading history, bank statements, tax position, existing debt, loan purpose, security and repayment capacity can all shape the outcome.' },
		{ title: 'Match the product to the cash-flow problem', description: 'A stock gap, unpaid invoice, equipment purchase, bank decline and job deposit may each need a different funding pathway.' },
		{ title: 'Avoid weak applications', description: 'Sending the wrong documents to the wrong lender wastes time and can make a viable business look unprepared.' },
	],
	docEyebrow: 'Prepare before timing gets tight',
	docHeading: 'Funding delays often start before the lender says anything',
	docBody: 'Owners often lose time because the lender asks for information that is not ready. If the funding is for stock, wages, equipment, supplier deposits or a job already won, every missing document can push the decision further away.',
	docCtaLabel: 'Read the requirements guide',
	docCtaHref: '/blog/business-loan-requirements-australia',
	checklist: [
		'ABN, trading history and business details',
		'Last 3 to 6 months of business bank statements',
		'BAS, GST records or financials for larger requests',
		'ATO position or payment-plan details if relevant',
		'Invoices, purchase orders or contracts tied to the funding need',
		'Asset quotes, supplier invoices or vehicle details',
		'Clear use of funds, amount needed and repayment source',
		'Existing debts, commitments and repayment rhythm',
	],
	pathwayEyebrow: 'Start with the reason cash is needed',
	pathwayHeading: 'Different funding problems need different pathways',
	pathwayCards: [
		{ title: 'A bigger job needs cash upfront', description: 'Materials, labour, mobilisation costs or supplier deposits may be due before the customer pays.', href: '/business-loans/working-capital', linkLabel: 'Read the guide' },
		{ title: 'Invoices are out, but cash has not landed', description: 'Invoice finance may fit some B2B businesses with eligible receivables and reliable debtors.', href: '/business-loans/invoice-finance', linkLabel: 'Read the guide' },
		{ title: 'Equipment is needed before revenue increases', description: 'Asset finance may match equipment cost to the period it helps the business earn.', href: '/business-loans/equipment-finance', linkLabel: 'Read the guide' },
		{ title: 'The bank said no, but the reason matters', description: 'A decline may be about policy, timing, security, documents or affordability. The next move depends on why.', href: '/business-loans/knocked-back-by-bank', linkLabel: 'Read the guide' },
		{ title: 'Tax or BAS pressure is tightening cash flow', description: 'Some situations need advice and payment-plan review before taking on more debt.', href: '/business-loans/tax-debt', linkLabel: 'Read the guide' },
		{ title: 'Stock or seasonal demand is coming', description: 'The risk is buying too late, buying too much, or using the wrong repayment structure.', href: '/business-loans/line-of-credit', linkLabel: 'Read the guide' },
	],
	declineHeading: 'A bank decline is information, not the end of the search',
	declineBody: 'The useful next step is not to apply everywhere. First find out whether the issue was security, serviceability, tax position, documents, industry appetite or loan purpose.',
	declineCtaLabel: 'What to do after a bank decline',
	declineCtaHref: '/business-loans/knocked-back-by-bank',
	guideHeading: 'Practical funding guides before you apply',
	guideCards: [
		{ title: 'Business loan requirements', description: 'What lenders may ask for before an SME applies: revenue, statements, tax position, use of funds, security and affordability.', href: '/blog/business-loan-requirements-australia', linkLabel: 'Read guide' },
		{ title: 'How lenders assess applications', description: 'The checks behind lender decisions, including documents, bank conduct, repayment capacity and product fit.', href: '/blog/how-business-lenders-assess-applications', linkLabel: 'Read guide' },
		{ title: 'Secured vs unsecured business loans', description: 'How security, guarantees, speed, pricing and repayment pressure change the funding path.', href: '/blog/secured-vs-unsecured-business-loans', linkLabel: 'Read guide' },
	],
	faqHeading: 'Frequently asked questions',
	faqs: [
		{ question: 'What does Comparison One do?', answer: 'Comparison One helps Australian business owners compare funding pathways by fit: use of funds, cash-flow timing, documents, security, repayment capacity and lender criteria. It is a comparison and enquiry pathway, not a lender.' },
		{ question: 'What does avoid applying blind mean?', answer: 'It means checking the likely product path and document requirements before sending an application to a lender that may not suit the situation.' },
		{ question: 'What documents should I prepare first?', answer: 'Start with ABN details, recent business bank statements, use of funds, amount needed, repayment source and any evidence tied to the funding need, such as invoices, contracts or asset quotes.' },
		{ question: 'What if my bank already declined me?', answer: 'Ask why before applying again. A decline reason can point to a better next step or show that preparation is needed before more applications.' },
		{ question: 'Is this financial advice?', answer: 'No. The information on Comparison One is general only. It does not consider your objectives, financial situation or needs. Speak with qualified advisers before making finance, tax or legal decisions.' },
	],
	finalHeading: 'Do not wait until the lender asks for documents',
	finalBody: 'If funding may be needed for a job, stock, equipment, invoices or cash-flow timing, start by checking what path fits and what information should be ready.',
	finalCtaLabel: 'Start my funding readiness check',
	finalCtaHref: '/quiz',
	seoTitle: 'Avoid Applying Blind for Business Funding | Comparison One',
	seoDescription: 'Check business funding readiness before applying. See what documents lenders may ask for and compare bank, non-bank and specialist funding paths by fit.',
}

export default defineType({
	name: 'c1.homepage',
	title: 'Comparison One Homepage',
	type: 'document',
	icon: HomeIcon,
	groups: [
		{ name: 'hero', title: 'Hero', default: true },
		{ name: 'sections', title: 'Sections' },
		{ name: 'faq', title: 'FAQ' },
		{ name: 'seo', title: 'SEO' },
	],
	initialValue: defaultHomepage,
	fields: [
		defineField({ name: 'title', type: 'string', group: 'hero', initialValue: defaultHomepage.title }),
		defineField({ name: 'heroEyebrow', title: 'Hero eyebrow', type: 'string', group: 'hero' }),
		defineField({ name: 'heroHeadline', title: 'Hero headline', type: 'string', group: 'hero', validation: (Rule) => Rule.required() }),
		defineField({ name: 'heroSubtitle', title: 'Hero subtitle', type: 'text', rows: 4, group: 'hero' }),
		defineField({ name: 'heroImage', title: 'Hero image path', type: 'string', group: 'hero', description: 'Use /finview/hero_img.png unless you are deliberately changing the Finwise hero asset.' }),
		defineField({ name: 'heroImageAlt', title: 'Hero image alt text', type: 'string', group: 'hero' }),
		defineField({ name: 'primaryCtaLabel', title: 'Funding widget button label', type: 'string', group: 'hero' }),
		defineField({ name: 'secondaryCtaLabel', type: 'string', group: 'hero' }),
		defineField({ name: 'secondaryCtaHref', type: 'string', group: 'hero' }),
		defineField({ name: 'trustStrip', type: 'string', group: 'hero' }),
		defineField({ name: 'whyEyebrow', type: 'string', group: 'sections' }),
		defineField({ name: 'whyHeading', type: 'string', group: 'sections' }),
		defineField({ name: 'whyBody', type: 'text', rows: 3, group: 'sections' }),
		defineField({ name: 'whyCards', type: 'array', group: 'sections', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'title', type: 'string' }), defineField({ name: 'description', type: 'text', rows: 3 })], preview: { select: { title: 'title', subtitle: 'description' } } })] }),
		defineField({ name: 'docEyebrow', title: 'Document section eyebrow', type: 'string', group: 'sections' }),
		defineField({ name: 'docHeading', title: 'Document section heading', type: 'string', group: 'sections' }),
		defineField({ name: 'docBody', title: 'Document section body', type: 'text', rows: 4, group: 'sections' }),
		defineField({ name: 'docCtaLabel', title: 'Document CTA label', type: 'string', group: 'sections' }),
		defineField({ name: 'docCtaHref', title: 'Document CTA href', type: 'string', group: 'sections' }),
		defineField({ name: 'checklist', type: 'array', group: 'sections', of: [defineArrayMember({ type: 'string' })] }),
		defineField({ name: 'pathwayEyebrow', type: 'string', group: 'sections' }),
		defineField({ name: 'pathwayHeading', type: 'string', group: 'sections' }),
		defineField({ name: 'pathwayCards', type: 'array', group: 'sections', of: [defineArrayMember({ type: 'object', fields: linkCardFields, preview: { select: { title: 'title', subtitle: 'description' } } })] }),
		defineField({ name: 'declineHeading', type: 'string', group: 'sections' }),
		defineField({ name: 'declineBody', type: 'text', rows: 3, group: 'sections' }),
		defineField({ name: 'declineCtaLabel', type: 'string', group: 'sections' }),
		defineField({ name: 'declineCtaHref', type: 'string', group: 'sections' }),
		defineField({ name: 'guideHeading', type: 'string', group: 'sections' }),
		defineField({ name: 'guideCards', type: 'array', group: 'sections', of: [defineArrayMember({ type: 'object', fields: linkCardFields, preview: { select: { title: 'title', subtitle: 'description' } } })] }),
		defineField({ name: 'finalHeading', type: 'string', group: 'sections' }),
		defineField({ name: 'finalBody', type: 'text', rows: 3, group: 'sections' }),
		defineField({ name: 'finalCtaLabel', type: 'string', group: 'sections' }),
		defineField({ name: 'finalCtaHref', type: 'string', group: 'sections' }),
		defineField({ name: 'faqHeading', type: 'string', group: 'faq' }),
		defineField({ name: 'faqs', type: 'array', group: 'faq', of: [defineArrayMember({ type: 'object', fields: [defineField({ name: 'question', type: 'string' }), defineField({ name: 'answer', type: 'text', rows: 4 })], preview: { select: { title: 'question', subtitle: 'answer' } } })] }),
		defineField({ name: 'seoTitle', type: 'string', group: 'seo' }),
		defineField({ name: 'seoDescription', type: 'text', rows: 3, group: 'seo' }),
	],
	preview: { select: { title: 'title', subtitle: 'heroHeadline' } },
})
